### ISSUE TITLE
Not working in Django==1.8.1

### ISSUE THREAD

**Issue by diegomatar** [aellerton/demo-allauth-bootstrap#12]
I followed the installing instructions, but I am getting an:
*ImportError at/ No module named context_processors*

I thought it was because the new TEMPLATE settings in Django 1.8, but even after updating settings_generated.py the error persists.

I also tried to run using Django 1.7, but got the same.. 

<img width="944" alt="screen shot 2015-07-24 at 3 30 46 pm" src="https://cloud.githubusercontent.com/assets/5478971/8881863/6051c772-3219-11e5-8bb9-3f9c1ef51da9.png">

Any ideas of how can I make it work?

Thanks!

**Comment by aellerton** [comment]
It used to work but the ``requirements.txt`` file specifies using the latest allauth. That means that your checkout got an updated version which has a change to how context processors work:

https://github.com/pennersr/django-allauth/commit/7a5838b3297aa907a182c02626cf141f21a50689

I'll post a fix soon.

Thanks for reporting!

**Comment by aellerton** [comment]
@diegomatar: please pull latest, ``make configure``, ``make rebuild`` and run again. Let me know if all ok.

**Comment by diegomatar** [comment]
It worked now, thanks!

2015-07-25 3:01 GMT-03:00 Andrew E <notifications@github.com>:
