### ISSUE TITLE
Whats make configure? Can't run this??

### ISSUE THREAD

**Issue by jimmynos** [aellerton/demo-allauth-bootstrap#13]
$ make configure   # Builds a seed.sql that can be used in `make rebuild`
$ make rebuild     # A bit better than `python manage.py syncdb`
$ make run         # The same as `python manage.py runserver`

Im using windows

**Comment by aellerton** [comment]
Windows doesn't have make by default, so this is to be expected. (You could
use nmake or cygwin but installing them just for this is arguably not the
best use of time.)

Read the Makefile and just run the commands directly. I use make only
because it's convenient for me but you don't have to.

**Comment by Tatoo988** [comment]
`sqlite3 db.sqlite3 < seed.sql
/bin/sh: 1: sqlite3: not found
Makefile:17: recipe for target 'initdb' failed
make: *** [initdb] Error 127
`

make rebuild not working in Ubuntu too. I'm Using ubuntu 15.04

**Comment by aellerton** [comment]
Is sqlite installed?

Try "which sqlite3" and see if you get "not found".

If so, install it:

https://iqbalnaved.wordpress.com/2014/07/10/how-to-install-sqlite-3-8-2-on-ubuntu-14-04-and-commands-for-creating-database-and-tables/

    sudo apt-get install sqlite3

**Comment by aellerton** [comment]
Assuming this is all fine.
