### ISSUE TITLE
Login view mixup

### ISSUE THREAD

**Issue by CadBrad** [aellerton/demo-allauth-bootstrap#16]
I have really enjoyed this template, but i'm having some issues with the view on the Login page. I'm very new to python and Django, so i'm a little confused as to how I could fix this. I traced the url back into the allauth directory inside the virtual environment and found where the login field order was referenced, but changing this had no effect at all. I've never tried to change anything close to this file location so i'm not sure what I would do exactly. The good news is that it still works perfectly!

I am on Linux Ubuntu 14.04 using 
Django==1.8.1
django-allauth==0.22.0
django-bootstrap3==7.0.1

![djangologin](https://cloud.githubusercontent.com/assets/17770993/17721861/14e34330-63f3-11e6-8b61-4a81c1a51bba.png)

**Comment by aellerton** [comment]
Hi Brad,
That's a strange one. Did it render the fields in that order out of the
box, or were there any changes you made locally at all?
A

**Comment by CadBrad** [comment]
This is how it came out of the box.  

The other thing is that the Signup page looks perfect, with email, password, and password again.

**Comment by aellerton** [comment]
Thanks.

Could be that allauth has had various releases since I last updated the
code.

I'll try to get time to pull the latest and see if that affects it...

**Comment by CadBrad** [comment]
Sounds great thanks so much!

**Comment by chabura** [comment]
Same issue here. Picking this up again. In previous auth the fix was in set_form_field. Appears to not be used now. Any ideas?

**Comment by chabura** [comment]
Fixed: 

in allauth/utils.py:

Replace the following function w/ what's below:

def set_form_field_order(form, fields_order):
    import collections
    if isinstance(form.fields, SortedDict):
        form.fields = collections.OrderedDict((f, form.fields[f])
                                  for f in fields_order)
    else:
        # Python 2.7+
        from collections import OrderedDict
        assert isinstance(form.fields, OrderedDict)
        form.fields = collections.OrderedDict((f, form.fields[f])
                                  for f in fields_order)

**Comment by CadBrad** [comment]
Works perfect for me, thanks for the speedy reply.

**Comment by aellerton** [comment]
@chabura do you mean you needed to modify the allauth source itself?

**Comment by ap133** [comment]
yes

**Comment by ap133** [comment]
yes
