### ISSUE TITLE
change syncdb to makemigrations

### ISSUE THREAD

**Issue by djchou** [aellerton/demo-allauth-bootstrap#6]
When databases are initialized using syncdb, changes to the models are not captured when running make migrations / migrate.  I changed the makefile's contents to

rebuild: 
    deldb migratedb initdb

and defined migratedb as 

migratedb:
    python manage.py makemigrations
    python manage.py migrate

**Comment by aellerton** [comment]
Thanks for these comments and sorry for my slow reply. This is on my todo list...

**Comment by aellerton** [comment]
Done in aa0aa0cada696d34d65a8415761d7a2448ed09e0 which also brings the sample up to latest stable Django (1.10.4) and Django-allauth (0.29.0)
