### ISSUE TITLE
Error creating super user

### ISSUE THREAD

**Issue by silentjay** [aellerton/demo-allauth-bootstrap#7]
When trying to create a superuser using the createsuperuser command I receive the error:

`self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
TypeError: create_superuser() takes exactly 4 arguments (2 given)`

I'm quite far through a project so can't be 100% sure it's down demo-allauth-bootstrap without testing a fresh project. However I see you inject the superuser using the make file so it could explain why this error wouldn't of occurred.

Anyway just incase a problem with demo-allauth-bootstrap I solved it by creating a custom user manager:

'class CustomUserManager(BaseUserManager):

```
def _create_user(self, email, password,
                 is_staff, is_superuser, **extra_fields):
    """
    Creates and saves a User with the given email and password.
    """
    now = timezone.now()
    if not email:
        raise ValueError('The given email must be set')
    email = self.normalize_email(email)
    user = self.model(email=email,
                      is_staff=is_staff, is_active=True,
                      is_superuser=is_superuser, last_login=now,
                      date_joined=now, **extra_fields)
    user.set_password(password)
    user.save(using=self._db)
    return user

def create_user(self, email, password=None, **extra_fields):
    return self._create_user(email, password, False, False,
                             **extra_fields)

def create_superuser(self, email, password, **extra_fields):
    return self._create_user(email, password, True, True,
                             **extra_fields)'
```

**Comment by aellerton** [comment]
Ah this is good. I'll integrate it. Thanks for the post and sorry it's taken me a while to reply.

**Comment by aellerton** [comment]
As of Django 1.10.4, this works without code change:

```
$ ./manage.py createsuperuser
Email address: foo@admin.test
Password:
Password (again):
Superuser created successfully.
```

Thanks so much for the report, and sorry it took me a long time to come back to it. 
A
