### ISSUE TITLE
Abstract User relation Error on make rebuild

### ISSUE THREAD

**Issue by trustfactors** [aellerton/demo-allauth-bootstrap#8]
Here's what happens:

  ~/c/demo-allauth-bootstrap (master) $ make rebuild
  rm -f db.sqlite3
  python manage.py syncdb --noinput
  CommandError: One or more models did not validate:
  account.emailaddress: 'user' has a relation with model allauthdemo_auth.DemoUser, which has either   not been installed or is abstract.
  admin.logentry: 'user' has a relation with model allauthdemo_auth.DemoUser, which has either not been installed or is abstract.
  auth.user: Model has been swapped out for 'allauthdemo_auth.DemoUser' which has not been installed or is abstract.
  socialaccount.socialaccount: 'user' has a relation with model allauthdemo_auth.DemoUser, which has either not been installed or is abstract.

make: *** [syncdb] Error 1

I'm using Django 1.6.5.

**Comment by trustfactors** [comment]
I was able to solve this by changing:

    AUTH_USER_MODEL = 'allauthdemo_auth.DemoUser'

to

    AUTH_USER_MODEL = 'auth.DemoUser'

**Comment by aellerton** [comment]
Nice! I don't know how that slipped through until now. Fixed now.

Thanks!
